# Generated by Django 4.0.6 on 2022-07-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='desc_produto',
            field=models.TextField(max_length=1200),
        ),
    ]
