# Generated by Django 4.0.6 on 2022-07-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_desc_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
    ]
