# Generated by Django 4.0.6 on 2022-08-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='linkUrl',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
